[dockerdev]
host = "0.0.0.0"
port = 9000
# LOGGING
log_level = "trace"
logs_path = "" # empty for STDOUT
log_to_stdout = true # additional logging to STDOUT
# NETLOG BACKUP
netlog_unix_socket_addr_dir  = "/var/tmp/serj-service"
netlog_unix_socket_file_name = "netlog-backup.sock"
# PROMETHEUS METRICS
prometheus_metrics_port = "2112"
prometheus_metrics_host = "0.0.0.0"
# POSGRES
postgres_port = "5432"
postgres_host = "postgres"
postgres_db_name = "serj_blogs"
# REDIS
redis_host = "redis"
redis_port = "6379"
# QUOTES FILE
quotes_csv_path = "./assets/quotes.csv"
# SENTRY
sentry_enabled = false
# GYMSTATS
gymstats_disk_api_root_path = "/var/gymstats"
# SPOTIFY TRACKER
spotify_redirect_uri = "http://localhost:9000/spotify/auth/redirect"
post_auth_redirect_url = "http://localhost:8080/spotify"
spotify_tracker_fire_interval_minutes = 10
# OTHER
login_rate_limit_allowed_per_min = 15

[development]
host = "localhost"
port = 9000
# LOGGING
log_level = "trace"
logs_path = "" # empty for STDOUT
log_to_stdout = true # additional logging to STDOUT
# NETLOG BACKUP
netlog_unix_socket_addr_dir  = "/var/tmp/serj-service"
netlog_unix_socket_file_name = "netlog-backup.sock"
# PROMETHEUS METRICS
prometheus_metrics_port = "2112"
prometheus_metrics_host = "localhost"
# POSGRES
postgres_port = "5432"
postgres_host = "localhost"
postgres_db_name = "serj_blogs"
# REDIS
redis_host = "localhost"
redis_port = "6379"
# QUOTES FILE
quotes_csv_path = "./assets/quotes.csv"
# SENTRY
sentry_enabled = false
# GYMSTATS
gymstats_disk_api_root_path = "/var/tmp/gymstats"
# SPOTIFY TRACKER
spotify_redirect_uri = "http://localhost:9000/spotify/auth/redirect"
post_auth_redirect_url = "http://localhost:8080/spotify"
spotify_tracker_fire_interval_minutes = 10
# OTHER
login_rate_limit_allowed_per_min = 15

[production]
host = "localhost"
port = 1988
# LOGGING
log_level = "trace"
logs_path = "/var/log/serj-tubin-backend/service.log"
log_to_stdout = false # additional logging to STDOUT
# NETLOG BACKUP
netlog_unix_socket_addr_dir  = "/var/tmp/serj-service" # TODO: change to use /var/run
netlog_unix_socket_file_name = "netlog-backup.sock"
# PROMETHEUS METRICS
prometheus_metrics_port = "2112"
prometheus_metrics_host = "localhost"
# POSGRES
postgres_port = "5432"
postgres_host = "localhost"
postgres_db_name = "serj_blogs"
# REDIS
redis_host = "162.55.179.82"
redis_port = "6379"
# QUOTES FILE
quotes_csv_path = "./assets/quotes.csv"
# SENTRY
sentry_enabled = true
# GYMSTATS
gymstats_disk_api_root_path = "/home/serj/gymstats-data"
# SPOTIFY TRACKER
spotify_redirect_uri = "https://h.serj-tubin.com/api/spotify/auth/redirect"
post_auth_redirect_url = "https://www.serj-tubin.com/spotify"
spotify_tracker_fire_interval_minutes = 30
# OTHER
login_rate_limit_allowed_per_min = 15
