version: "3.7"

services:
  aerospike:
    platform: "linux/amd64"

  redis:
    platform: "linux/amd64"

  postgres:
    platform: "linux/amd64"

  adminer:
    platform: "linux/amd64"

  prometheus:
    platform: "linux/amd64"

  grafana:
      platform: "linux/amd64"

  alertmanager:
    platform: "linux/amd64"

  cadvisor:
    platform: "linux/amd64"
