version: "3.7"
  
# redis for the auth service (maybe others later)
# remote connect:
#   - redis-cli -h host -p port -a password

networks:
  redis-network:

services:
  redis:
    image: redis
    networks:
      redis-network:
    command: redis-server --appendonly yes --requirepass ${SERJ_REDIS_PASS}
    container_name: st-redis
    volumes:
     - /home/serj/docker-redis-data:/data
    ports:
     - 6379:6379
