version: "3.7"

# note 27 nov 22:
# small log:
# - removed old prometheus running on misc
# - added all docker related files to run prometheus in docker on misc server
# - old metrics are still left (~3GB) at: /var/lib/prometheus/metrics2
# - old systemd prometheus is down (but not removed)
#   - sudo systemctl status prometheus.service
#   - /lib/systemd/system/prometheus.service
# - grafana is also running on misc (directly)
#   - systemctl list-units --type=service | grep grafana
#   - was updated to v9.2 today on misc server
# TODOs:
#   - migrate or remove old prometheus data (/var/lib/prometheus/metrics2)
#     - new data is at (~/docker-data-prometheus) used by docker container
#   - remove old systemd related prometheus data
#
# TODO:
# - alertmanager has been added, but not configured

# TODO / Changes (june 2023):
# - add node_exporter to all 4 servers: https://prometheus.io/docs/guides/node-exporter/
#   - added to misc server (check executed commands with: history | grep node_exporter)
#   - check ./docker/prometheus-for-misc-server/prometheus.yml !!
# - configure them to export metrics to prometheus
# - add alarms/triggers that will send emails when disk space is low
# - node exporter added to all nodes (ssr, ssr2, misc, conf) and boards created in grafana
# - prometheus scrape targets visible at: https://prometheus.serj-tubin.com/targets?search=
# - reload config with: curl -X POST http://localhost:9090/-/reload

networks:
  prometheus-network:

services:
  prometheus:
    image: prom/prometheus:v2.40.3
    networks:
      prometheus-network:
    restart: always
    volumes:
      - ./prometheus-for-misc-server/:/etc/prometheus/
      - /mnt/misc-serj-volume-nbg1-1/docker-data-prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle' # allow restart on the fly with curl -X POST http://localhost:9000/-/reload
      - '--storage.tsdb.retention.time=800d' # 800d = a bit over 2 years; https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager
    networks:
      prometheus-network:
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./prometheus-for-misc-server/alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
