name: CI
on:
  pull_request:
jobs:
  golangci:
    name: linter checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
  unit-tests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checks-out the repository under $GITHUB_WORKSPACE
        with:
          fetch-depth: 1
          go-version: '1.16.0'
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - name: Run unit tests
        run: go test ./...