name: CI
on:
  pull_request:
jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@v0.0.9
        with:
          fail-on-vuln: true
  golangci:
    name: linter checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.3
      - uses: actions/checkout@v3
      - name: Run linter
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          args: --timeout 5m
  tests:
    name: tests
    runs-on: ubuntu-latest
    container: node:latest
    services:
      # Label used to access the service container
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: serj_blogs
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_HOST_AUTH_METHOD: trust
          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
      redis:
        image: redis:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3 # checks-out the repository under $GITHUB_WORKSPACE
        with:
          fetch-depth: 1
          go-version: '1.20.3'
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20.3'
      - name: Get PSQL CLI
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client
      - name: Initialize DB
        run: psql -f sql/db_schema.sql postgresql://postgres:postgres@postgres:5432/serj_blogs
      - name: Run tests
        run: make test-all
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          REDIS_HOST: redis
          REDIS_PASS: <remove>
