name: unit-tests
on:
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checks-out the repository under $GITHUB_WORKSPACE
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v2
      - name: Run unit tests
        run: go test ./...