name: VulnCheck

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * *' # every day at 6am

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@v0.10.1
        with:
          go-version: 1.20.5
          package: ./...
          fail-on-vuln: true
